"""initial

Revision ID: 57b7f62e95e3
Revises: 
Create Date: 2026-07-16 14:27:28.315007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b7f62e95e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balance_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unit_price_at_time', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('balance_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balance_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_balance_transactions_customer_id'), ['customer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balance_transactions_customer_id'))
        batch_op.drop_index(batch_op.f('ix_balance_transactions_created_at'))

    op.drop_table('balance_transactions')
    op.drop_table('products')
    op.drop_table('customers')
    # ### end Alembic commands ###
